const InitialParkStates = [
    {
        id: '1',
        park_id: '1',
        state_code: 'ME',
        state: 'Maine',
    },
    {
        id: '2',
        park_id: '2',
        state_code: 'AS',
        state: 'American Samoa',
    },
    {
        id: '3',
        park_id: '3',
        state_code: 'UT',
        state: 'Utah',
    },
    {
        id: '4',
        park_id: '4',
        state_code: 'SD',
        state: 'South Dakota',
    },
    {
        id: '5',
        park_id: '5',
        state_code: 'TX',
        state: 'Texas',
    },
    {
        id: '6',
        park_id: '6',
        state_code: 'FL',
        state: 'Florida',
    },
    {
        id: '7',
        park_id: '7',
        state_code: 'CO',
        state: 'Colorado',
    },
    {
        id: '8',
        park_id: '8',
        state_code: 'UT',
        state: 'Utah',
    },
    {
        id: '9',
        park_id: '9',
        state_code: 'UT',
        state: 'Utah',
    },
    {
        id: '10',
        park_id: '10',
        state_code: 'UT',
        state: 'Utah',
    },
    {
        id: '11',
        park_id: '11',
        state_code: 'NM',
        state: 'New Mexico',
    },
    {
        id: '12',
        park_id: '12',
        state_code: 'CA',
        state: 'California',
    },
    {
        id: '13',
        park_id: '13',
        state_code: 'SC',
        state: 'South Carolina',
    },
    {
        id: '14',
        park_id: '13',
        state_code: 'VA',
        state: 'Virginia',
    },
    {
        id: '15',
        park_id: '14',
        state_code: 'OR',
        state: 'Oregon',
    },
    {
        id: '16',
        park_id: '15',
        state_code: 'OH',
        state: 'Ohio',
    },
    {
        id: '17',
        park_id: '16',
        state_code: 'CA',
        state: 'California',
    },
    {
        id: '18',
        park_id: '16',
        state_code: 'NV',
        state: 'Nevada',
    },
    {
        id: '19',
        park_id: '17',
        state_code: 'AK',
        state: 'Alaska',
    },
    {
        id: '20',
        park_id: '18',
        state_code: 'FL',
        state: 'Florida',
    },
    {
        id: '21',
        park_id: '19',
        state_code: 'FL',
        state: 'Florida',
    },
    {
        id: '22',
        park_id: '20',
        state_code: 'AK',
        state: 'Alaska',
    },
    {
        id: '23',
        park_id: '21',
        state_code: 'MO',
        state: 'Missouri',
    },
    {
        id: '24',
        park_id: '22',
        state_code: 'AK',
        state: 'Alaska',
    },
    {
        id: '25',
        park_id: '23',
        state_code: 'MT',
        state: 'Montana',
    },
    {
        id: '26',
        park_id: '24',
        state_code: 'AZ',
        state: 'Arizona',
    },
    {
        id: '27',
        park_id: '25',
        state_code: 'WY',
        state: 'Wyoming',
    },
    {
        id: '28',
        park_id: '26',
        state_code: 'NV',
        state: 'Nevada',
    },
    {
        id: '29',
        park_id: '27',
        state_code: 'CO',
        state: 'Colorado',
    },
    {
        id: '30',
        park_id: '28',
        state_code: 'TN',
        state: 'Tennessee',
    },
    {
        id: '31',
        park_id: '28',
        state_code: 'NC',
        state: 'North Carolina',
    },
    {
        id: '32',
        park_id: '29',
        state_code: 'TX',
        state: 'Texas',
    },
    {
        id: '33',
        park_id: '30',
        state_code: 'HI',
        state: 'Hawaii',
    },
    {
        id: '34',
        park_id: '31',
        state_code: 'HI',
        state: 'Hawaii',
    },
    {
        id: '35',
        park_id: '32',
        state_code: 'AR',
        state: 'Arkansas',
    },
    {
        id: '36',
        park_id: '33',
        state_code: 'IN',
        state: 'Indiana',
    },
    {
        id: '37',
        park_id: '34',
        state_code: 'MI',
        state: 'Michigan',
    },
    {
        id: '38',
        park_id: '35',
        state_code: 'CA',
        state: 'California',
    },
    {
        id: '39',
        park_id: '36',
        state_code: 'AK',
        state: 'Alaska',
    },
    {
        id: '40',
        park_id: '37',
        state_code: 'AK',
        state: 'Alaska',
    },
    {
        id: '41',
        park_id: '38',
        state_code: 'CA',
        state: 'California',
    },
    {
        id: '42',
        park_id: '39',
        state_code: 'AK',
        state: 'Alaska',
    },
    {
        id: '43',
        park_id: '40',
        state_code: 'AK',
        state: 'Alaska',
    },
    {
        id: '44',
        park_id: '41',
        state_code: 'CA',
        state: 'California',
    },
    {
        id: '45',
        park_id: '42',
        state_code: 'KY',
        state: 'Kentucky',
    },
    {
        id: '46',
        park_id: '43',
        state_code: 'CO',
        state: 'Colorado',
    },
    {
        id: '47',
        park_id: '44',
        state_code: 'WA',
        state: 'Washington',
    },
    {
        id: '48',
        park_id: '45',
        state_code: 'WV',
        state: 'West Virginia',
    },
    {
        id: '49',
        park_id: '46',
        state_code: 'WA',
        state: 'Washington',
    },

    {
        id: '50',
        park_id: '47',
        state_code: 'WA',
        state: 'Washington',
    },
    {
        id: '51',
        park_id: '48',
        state_code: 'AZ',
        state: 'Arizona',
    },
    {
        id: '52',
        park_id: '49',
        state_code: 'CA',
        state: 'California',
    },
    {
        id: '53',
        park_id: '50',
        state_code: 'CA',
        state: 'California',
    },
    {
        id: '54',
        park_id: '51',
        state_code: 'CO',
        state: 'Colorado',
    },
    {
        id: '55',
        park_id: '52',
        state_code: 'AZ',
        state: 'Arizona',
    },
    {
        id: '56',
        park_id: '53',
        state_code: 'CA',
        state: 'California',
    },
    {
        id: '57',
        park_id: '54',
        state_code: 'VA',
        state: 'Virginia',
    },
    {
        id: '58',
        park_id: '55',
        state_code: 'ND',
        state: 'North Dakota',
    },
    {
        id: '59',
        park_id: '56',
        state_code: 'VI',
        state: 'Virgin Islands',
    },
    {
        id: '60',
        park_id: '57',
        state_code: 'MN',
        state: 'Minnesota',
    },
    {
        id: '61',
        park_id: '58',
        state_code: 'NM',
        state: 'New Mexico',
    },
    {
        id: '62',
        park_id: '59',
        state_code: 'SD',
        state: 'South Dakota',
    },
    {
        id: '63',
        park_id: '60',
        state_code: 'AK',
        state: 'Alaska',
    },
    {
        id: '64',
        park_id: '61',
        state_code: 'WY',
        state: 'Idaho',
    },
    {
        id: '65',
        park_id: '61',
        state_code: 'MO',
        state: 'Montana',
    },
    {
        id: '66',
        park_id: '61',
        state_code: 'ID',
        state: 'Idaho',
    },
    {
        id: '67',
        park_id: '62',
        state_code: 'CA',
        state: 'California',
    },
    {
        id: '68',
        park_id: '63',
        state_code: 'UT',
        state: 'Utah',
    },
]

export default InitialParkStates
