
const InitialAddons = [
	{
		id:'1',
		name: 'Hiking Poles I',
		description: 'Reduces the interval for pace increases, allowing the user to get a pace increase faster.',
		level: 1,
		effect_type: 'pace_increase_interval',
		effect_value: 780 , // 13 - 2min faster pace increase interval
		required_total_miles: 0,
		image_url: 'HikingPoles1.png',
		price: 25,
		created_at: Date.now(),
		updated_at: Date.now(),
	},
	{
		id:'2',
		name: 'Hiking Poles II',
		description: 'Reduces the interval for pace increases, allowing the user to get a pace increase faster.',
		level: 2,
		effect_type: 'pace_increase_interval',
		effect_value: 600, // 20% faster pace increase interval
		required_total_miles: 50,
		image_url: 'HikingPoles2.png',
		price: 50,
		created_at: Date.now(),
		updated_at: Date.now(),
	},
	{
		id:'3',
		name: 'Hiking Poles III',
		description: 'Reduces the interval for pace increases, allowing the user to get a pace increase faster.',
		level: 3,
		effect_type: 'pace_increase_interval',
		effect_value: 580, // 30% faster pace increase interval
		required_total_miles: 100,
		image_url: 'HikingPoles3.png',
		price: 100,
		created_at: Date.now(),
		updated_at: Date.now(),
	},
	{
		id:'4',
		name: 'Water Bottle I',
		description: 'Reduces the break time, allowing the user to resume hiking faster.',
		level: 1,
		effect_type: 'break_time_reduction',
		effect_value: 0.8, // 20% break time reduction
		required_total_miles: 0,
		price: 25,
		image_url: 'WaterBottle1.png',
		created_at: Date.now(),
		updated_at: Date.now(),
	},
	{
		id:'5',
		name: 'Water Bottle II',
		description: 'Reduces the break time, allowing the user to resume hiking faster.',
		level: 2,
		effect_type: 'break_time_reduction',
		effect_value: 0.6, // 40% break time reduction
		required_total_miles: 50,
		image_url: 'WaterBottle2.png',
		price: 50,
		created_at: Date.now(),
		updated_at: Date.now(),
	},
	{
		id:'6',
		name: 'Water Bottle III',
		description: 'Allows the user to skip breaks.',
		level: 3,
		effect_type: 'break_time_reduction',
		effect_value: 0, // Break time skipped
		required_total_miles: 100,
		price: 100,
		image_url: 'WaterBottle3.png',
		created_at: Date.now(),
		updated_at: Date.now(),
	},
	{
		id:'7',
		name: 'Trail Mix I',
		description: 'Increases the value of the pace increase during each interval.',
		level: 1,
		effect_type: 'pace_increase_value',
		effect_value: .25, // 10% higher pace increase
		required_total_miles: 0,
		image_url: 'TrailMix1.png',
		price: 25,
		created_at: Date.now(),
		updated_at: Date.now(),
	},
	{
		id:'8',
		name: 'Trail Mix II',
		description: 'Increases the value of the pace increase during each interval.',
		level: 2,
		effect_type: 'pace_increase_value',
		effect_value: .5, // 20% higher pace increase
		required_total_miles: 50,
		image_url: 'TrailMix2.png',
		price: 50,
		created_at: Date.now(),
		updated_at: Date.now(),
	},
	{
		id:'9',
		name: 'Trail Mix III',
		description: 'Increases the value of the pace increase during each interval.',
		level: 3,
		effect_type: 'pace_increase_value',
		effect_value: .75, // 30% higher pace increase
		required_total_miles: 100,
		image_url: 'TrailMix3.png',
		price: 100,
		created_at: Date.now(),
		updated_at: Date.now(),
	},
	{
		id:'10',
		name: 'First Aid I',
		description: 'Reduces the penalty for pausing or touching the phone during a session.',
		level: 1,
		effect_type: 'penalty_reduction',
		effect_value: 0.75, //  penalty
		required_total_miles: 0,
		image_url: 'FirstAid1.png',
		price: 25,
		created_at: Date.now(),
		updated_at: Date.now(),
	},
	{
		id:'11',
		name: 'First Aid II',
		description: 'Reduces the penalty for pausing or touching the phone during a session.',
		level: 2,
		effect_type: 'penalty_reduction',
		effect_value: 0.5, //  reduction in penalty
		required_total_miles: 50,
		image_url: 'FirstAid2.png',
		price: 50,
		created_at: Date.now(),
		updated_at: Date.now(),
	},
	{
		id:'12',
		name: 'First Aid III',
		description: 'Reduces the penalty for pausing or touching the phone during a session.',
		level: 3,
		effect_type: 'penalty_reduction',
		effect_value: 0.25, // reduction in penalty
		required_total_miles: 100,
		image_url: 'FirstAid3.png',
		price: 100,
		created_at: Date.now(),
		updated_at: Date.now(),
	},
	{
		id:'13',
		name: 'Running Shoes I',
		description: 'Increases the maximum pace that can be achieved during a session.',
		level: 1,
		effect_type: 'max_pace_increase',
		effect_value: 5, // Increase max pace to 5 mph
		required_total_miles: 0,
		image_url: 'RunningShoes1.png',
		price: 25,
		created_at: Date.now(),
		updated_at: Date.now(),
	},
	{
		id:'14',
		name: 'Running Shoes II',
		description: 'Increases the maximum pace that can be achieved during a session.',
		level: 2,
		effect_type: 'max_pace_increase',
		effect_value: 6.5, // Increase max pace to 6.5 mph
		required_total_miles: 50,
		image_url: 'RunningShoes2.png',
		price: 50,
		created_at: Date.now(),
		updated_at: Date.now(),
	},
	{
		id:'15',
		name: 'Running Shoes III',
		description: 'Increases the maximum pace that can be achieved during a session.',
		level: 3,
		effect_type: 'max_pace_increase',
		effect_value: 8, // Increase max pace to 8 mph
		required_total_miles: 100,
		image_url: 'RunningShoes3.png',
		price: 100,
		created_at: Date.now(),
		updated_at: Date.now(),
	},
	{
		id:'16',
		name: 'Treasure Map I',
		description: 'Increases the number of trail tokens earned for trail completion.',
		level: 1,
		effect_type: 'trail_token_bonus',
		effect_value: .1, // Earn 10% additional tokens
		required_total_miles: 0,
		image_url: 'TreasureMap1.png',
		price: 25,
		created_at: Date.now(),
		updated_at: Date.now(),
	},
	{
		id:'17',
		name: 'Treasure Map II',
		description: 'Increases the number of trail tokens earned for trail completion.',
		level: 2,
		effect_type: 'trail_token_bonus',
		effect_value: .2, // Earn 20% additional tokens
		required_total_miles: 50,
		image_url: 'TreasureMap2.png',
		price: 50,
		created_at: Date.now(),
		updated_at: Date.now(),
	},
	{
		id:'18',
		name: 'Treasure Map III',
		description: 'Increases the number of trail tokens earned for trail completion.',
		level: 3,
		effect_type: 'trail_token_bonus',
		effect_value: .3, // Earn 30% additional tokens
		required_total_miles: 100,
		image_url: 'TreasureMap3.png',
		price: 100,
		created_at: Date.now(),
		updated_at: Date.now(),
	},
	{
		id:'19',
		name: 'Ultralight I',
		description: 'Increases the minimum/starting pace that can be achieved during a session.',
		level: 1,
		effect_type: 'min_pace_increase',
		effect_value: 2.5, // Increase min pace to 5 mph
		required_total_miles: 0,
		image_url: 'Ultralight1.png',
		price: 25,
		created_at: Date.now(),
		updated_at: Date.now(),
	},
	{
		id:'20',
		name: 'Ultralight II',
		description: 'Increases the minimum/starting pace that can be achieved during a session.',
		level: 2,
		effect_type: 'min_pace_increase',
		effect_value: 3, // Increase min pace to 6.5 mph
		required_total_miles: 50,
		image_url: 'Ultralight2.png',
		price: 50,
		created_at: Date.now(),
		updated_at: Date.now(),
	},
	{
		id:'21',
		name: 'Ultralight III',
		description: 'Increases the minimum/starting pace that can be achieved during a session.',
		level: 3,
		effect_type: 'min_pace_increase',
		effect_value: 4, // Increase min pace to 8 mph
		required_total_miles: 100,
		image_url: 'Ultralight3.png',
		price: 100,
		created_at: Date.now(),
		updated_at: Date.now(),
	},


];

export default InitialAddons;
