interface Rank {
  level: string;
  group: string;
  image?: any;
  range: number[];
  title: string;
}
const Ranks: Rank[] = [
  {
    level: '1',
    group: 'Beginner',
    image: require('../../assets/RankBadges/beginner.png'),
    range: [-Infinity, 0.24],
    title: 'Trailblazer',
  },
  {
    level: '2',
    group: 'Beginner',
    image: require('../../assets/RankBadges/beginner.png'),
    range: [0.25, 0.49],
    title: 'Pathfinder',
  },
  {
    level: '3',
    group: 'Beginner',
    image: require('../../assets/RankBadges/beginner.png'),
    range: [0.5, 0.74],
    title: 'Trekker',
  },
  {
    level: '4',
    group: 'Beginner',
    image: require('../../assets/RankBadges/beginner.png'),
    range: [0.75, 0.99],
    title: 'Explorer',
  },
  {
    level: '5',
    group: 'Beginner',
    image: require('../../assets/RankBadges/beginner.png'),
    range: [1.0, 1.49],
    title: 'Adventurer',
  },
  {
    level: '6',
    group: 'Beginner',
    image: require('../../assets/RankBadges/beginner.png'),
    range: [1.5, 1.99],
    title: 'Wayfarer',
  },
  {
    level: '7',
    group: 'Beginner',
    image: require('../../assets/RankBadges/beginner.png'),
    range: [2.0, 2.49],
    title: 'Pioneer',
  },
  {
    level: '8',
    group: 'Beginner',
    image: require('../../assets/RankBadges/beginner.png'),
    range: [2.5, 2.99],
    title: 'Mountaineer',
  },
  {
    level: '9',
    group: 'Beginner',
    image: require('../../assets/RankBadges/beginner.png'),
    range: [3.0, 3.49],
    title: 'Trail Master',
  },

  {
    level: '10',
    group: 'Amateur',
    image: require('../../assets/RankBadges/amateur.png'),

    range: [3.5, 4.49],
    title: 'Summit Seeker',
  },
  {
    level: '11',
    group: 'Amateur',
    image: require('../../assets/RankBadges/amateur.png'),
    range: [4.5, 5.49],
    title: 'Wilderness Roamer',
  },
  {
    level: '12',
    group: 'Amateur',
    image: require('../../assets/RankBadges/amateur.png'),
    range: [5.5, 6.49],
    title: 'Nature Stalker',
  },
  {
    level: '13',
    group: 'Amateur',
    image: require('../../assets/RankBadges/amateur.png'),
    range: [6.5, 7.49],
    title: 'Scenic Voyager',
  },
  {
    level: '14',
    group: 'Amateur',
    image: require('../../assets/RankBadges/amateur.png'),
    range: [7.5, 8.49],
    title: 'Canyon Conqueror',
  },
  {
    level: '15',
    group: 'Amateur',
    image: require('../../assets/RankBadges/amateur.png'),
    range: [8.5, 9.99],
    title: 'Ridge Runner',
  },
  {
    level: '16',
    group: 'Amateur',
    image: require('../../assets/RankBadges/amateur.png'),
    range: [10.0, 11.5],
    title: 'Peak Pursuer',
  },
  {
    level: '17',
    group: 'Amateur',
    image: require('../../assets/RankBadges/amateur.png'),
    range: [11.5, 12.99],
    title: 'Trailblazer Elite',
  },
  {
    level: '18',
    group: 'Amateur',
    image: require('../../assets/RankBadges/amateur.png'),
    range: [13.0, 14.49],
    title: 'Alpine Specialist',
  },
  {
    level: '19',
    group: 'Amateur',
    image: require('../../assets/RankBadges/amateur.png'),
    range: [14.5, 15.99],
    title: 'Expeditionist',
  },
  //
  {
    level: '20',
    group: 'Intermediate',
    image: require('../../assets/RankBadges/intermediate.png'),
    range: [16.0, 17.99],
    title: 'Mountain Maestro',
  },
  {
    level: '21',
    group: 'Intermediate',
    image: require('../../assets/RankBadges/intermediate.png'),
    range: [18.0, 19.99],
    title: 'Geology Enthusiast',
  },
  {
    level: '22',
    group: 'Intermediate',
    image: require('../../assets/RankBadges/intermediate.png'),
    range: [20.0, 21.99],
    title: 'Forest Navigator',
  },
  {
    level: '23',
    group: 'Intermediate',
    image: require('../../assets/RankBadges/intermediate.png'),
    range: [22.0, 23.99],
    title: 'Serene Wanderer',
  },
  {
    level: '24',
    group: 'Intermediate',
    image: require('../../assets/RankBadges/intermediate.png'),
    range: [24.0, 25.99],
    title: 'River Rover',
  },
  {
    level: '25',
    group: 'Intermediate',
    image: require('../../assets/RankBadges/intermediate.png'),
    range: [26.0, 28.49],
    title: 'Plateau Expert',
  },
  {
    level: '26',
    group: 'Intermediate',
    image: require('../../assets/RankBadges/intermediate.png'),
    range: [28.5, 30.99],
    title: 'Valley Discoverer',
  },
  {
    level: '27',
    group: 'Intermediate',
    image: require('../../assets/RankBadges/intermediate.png'),
    range: [31.0, 33.49],
    title: 'Summit Strider',
  },
  {
    level: '28',
    group: 'Intermediate',
    image: require('../../assets/RankBadges/intermediate.png'),
    range: [33.5, 35.99],
    title: 'Backcountry Maestro',
  },
  {
    level: '29',
    group: 'Intermediate',
    image: require('../../assets/RankBadges/intermediate.png'),
    range: [36.0, 38.49],
    title: 'Nature Whisperer',
  },
  //
  {
    level: '30',
    group: 'Journeyman',
    image: require('../../assets/RankBadges/journeyman.png'),
    range: [38.5, 41.49],
    title: 'Wilderness Guardian',
  },
  {
    level: '31',
    group: 'Journeyman',
    image: require('../../assets/RankBadges/journeyman.png'),
    range: [41.5, 44.49],
    title: 'Trail Connoisseur',
  },
  {
    level: '32',
    group: 'Journeyman',
    image: require('../../assets/RankBadges/journeyman.png'),
    range: [44.5, 47.49],
    title: 'Peak Prowler',
  },
  {
    level: '33',
    group: 'Journeyman',
    image: require('../../assets/RankBadges/journeyman.png'),
    range: [47.5, 50.49],
    title: 'Canyon Seeker',
  },
  {
    level: '34',
    group: 'Journeyman',
    image: require('../../assets/RankBadges/journeyman.png'),
    range: [50.5, 53.49],
    title: 'Wilderness Guru',
  },
  {
    level: '35',
    group: 'Journeyman',
    image: require('../../assets/RankBadges/journeyman.png'),
    range: [53.5, 56.99],
    title: 'Scenic Observer',
  },
  {
    level: '36',
    group: 'Journeyman',
    image: require('../../assets/RankBadges/journeyman.png'),
    range: [57.0, 60.49],
    title: 'Vista Seeker',
  },
  {
    level: '37',
    group: 'Journeyman',
    image: require('../../assets/RankBadges/journeyman.png'),
    range: [60.5, 63.99],
    title: 'Adventure Aficionado',
  },
  {
    level: '38',
    group: 'Journeyman',
    image: require('../../assets/RankBadges/journeyman.png'),
    range: [64.0, 67.49],
    title: 'Ridge Rover',
  },
  {
    level: '39',
    group: 'Journeyman',
    image: require('../../assets/RankBadges/journeyman.png'),
    range: [67.5, 70.99],
    title: 'Exploration Specialist',
  },
  //
  {
    level: '40',
    group: 'Advanced',
    image: require('../../assets/RankBadges/advanced.png'),
    range: [71.0, 74.99],
    title: 'Nature Conqueror',
  },
  {
    level: '41',
    group: 'Advanced',
    image: require('../../assets/RankBadges/advanced.png'),
    range: [75.0, 78.99],
    title: 'Mountain Maven',
  },
  {
    level: '42',
    group: 'Advanced',
    image: require('../../assets/RankBadges/advanced.png'),
    range: [79.0, 82.99],
    title: 'Summit Expert',
  },
  {
    level: '43',
    group: 'Advanced',
    image: require('../../assets/RankBadges/advanced.png'),
    range: [83.0, 86.99],
    title: 'Forest Conqueror',
  },
  {
    level: '44',
    group: 'Advanced',
    image: require('../../assets/RankBadges/advanced.png'),
    range: [87.0, 90.99],
    title: 'Wilderness Nomad',
  },
  {
    level: '45',
    group: 'Advanced',
    image: require('../../assets/RankBadges/advanced.png'),
    range: [91.0, 95.49],
    title: 'Scenic Savant',
  },
  {
    level: '46',
    group: 'Advanced',
    image: require('../../assets/RankBadges/advanced.png'),
    range: [95.5, 99.99],
    title: 'Canyon Master',
  },
  {
    level: '47',
    group: 'Advanced',
    image: require('../../assets/RankBadges/advanced.png'),
    range: [100.0, 104.49],
    title: 'Alpine Ace',
  },
  {
    level: '48',
    group: 'Advanced',
    image: require('../../assets/RankBadges/advanced.png'),
    range: [104.5, 108.99],
    title: 'Valley Voyager',
  },
  {
    level: '49',
    group: 'Advanced',
    image: require('../../assets/RankBadges/advanced.png'),
    range: [109.0, 113.49],
    title: 'Trailblazer Prodigy',
  },
  //
  {
    level: '50',
    group: 'Experienced',
    image: require('../../assets/RankBadges/experienced.png'),
    range: [113.5, 118.49],
    title: 'Expedition Captain',
  },
  {
    level: '51',
    group: 'Experienced',
    image: require('../../assets/RankBadges/experienced.png'),
    range: [118.5, 123.49],
    title: 'Wilderness Virtuoso',
  },
  {
    level: '52',
    group: 'Experienced',
    image: require('../../assets/RankBadges/experienced.png'),
    range: [123.5, 128.49],
    title: 'Peak Pioneer',
  },
  {
    level: '53',
    group: 'Experienced',
    image: require('../../assets/RankBadges/experienced.png'),
    range: [128.5, 133.49],
    title: 'Nature Maven',
  },
  {
    level: '54',
    group: 'Experienced',
    image: require('../../assets/RankBadges/experienced.png'),
    range: [133.5, 138.49],
    title: 'Adventure Pro',
  },
  {
    level: '55',
    group: 'Experienced',
    image: require('../../assets/RankBadges/experienced.png'),
    range: [138.5, 143.99],
    title: 'Trail Titan',
  },
  {
    level: '56',
    group: 'Experienced',
    image: require('../../assets/RankBadges/experienced.png'),
    range: [144.0, 149.49],
    title: 'Mountain Monarch',
  },
  {
    level: '57',
    group: 'Experienced',
    image: require('../../assets/RankBadges/experienced.png'),
    range: [149.5, 154.99],
    title: 'Scenic Guru',
  },
  {
    level: '58',
    group: 'Experienced',
    image: require('../../assets/RankBadges/experienced.png'),
    range: [155.0, 160.49],
    title: 'Expedition Leader',
  },
  {
    level: '59',
    group: 'Experienced',
    image: require('../../assets/RankBadges/experienced.png'),
    range: [160.5, 165.99],
    title: 'Summit Maestro',
  },
  //
  {
    level: '60',
    group: 'Master',
    image: require('../../assets/RankBadges/master.png'),
    range: [166.0, 171.99],
    title: 'Backcountry Legend',
  },
  {
    level: '61',
    group: 'Master',
    image: require('../../assets/RankBadges/master.png'),
    range: [172.0, 177.99],
    title: 'Trailblazing Master',
  },
  {
    level: '62',
    group: 'Master',
    image: require('../../assets/RankBadges/master.png'),
    range: [178.0, 183.99],
    title: 'Peak Dominator',
  },
  {
    level: '63',
    group: 'Master',
    image: require('../../assets/RankBadges/master.png'),
    range: [184.0, 189.99],
    title: 'Canyon Commandant',
  },
  {
    level: '64',
    group: 'Master',
    image: require('../../assets/RankBadges/master.png'),
    range: [190.0, 195.99],
    title: 'Wilderness Sage',
  },
  {
    level: '65',
    group: 'Master',
    image: require('../../assets/RankBadges/master.png'),
    range: [196.0, 202.49],
    title: 'Scenic Legend',
  },
  {
    level: '66',
    group: 'Master',
    image: require('../../assets/RankBadges/master.png'),
    range: [202.5, 208.99],
    title: 'Alpine Luminary',
  },
  {
    level: '67',
    group: 'Master',
    image: require('../../assets/RankBadges/master.png'),
    range: [209.0, 215.49],
    title: 'Exploration Maestro',
  },
  {
    level: '68',
    group: 'Master',
    image: require('../../assets/RankBadges/master.png'),
    range: [215.5, 221.99],
    title: 'Summit Sentinel',
  },
  {
    level: '69',
    group: 'Master',
    image: require('../../assets/RankBadges/master.png'),
    range: [222.0, 228.49],
    title: 'Nature Virtuoso',
  },
  //
  {
    level: '70',
    group: 'Expert',
    image: require('../../assets/RankBadges/expert.png'),
    range: [228.5, 235.49],
    title: 'Trail Conqueror',
  },
  {
    level: '71',
    group: 'Expert',
    image: require('../../assets/RankBadges/expert.png'),
    range: [235.5, 242.49],
    title: 'Mountain Marvel',
  },
  {
    level: '72',
    group: 'Expert',
    image: require('../../assets/RankBadges/expert.png'),
    range: [242.5, 249.49],
    title: 'Wilderness Wizard',
  },
  {
    level: '73',
    group: 'Expert',
    image: require('../../assets/RankBadges/expert.png'),
    range: [249.5, 256.49],
    title: 'Scenic Savant',
  },
  {
    level: '74',
    group: 'Expert',
    image: require('../../assets/RankBadges/expert.png'),
    range: [256.5, 263.49],
    title: 'Backcountry Guru',
  },
  {
    level: '75',
    group: 'Expert',
    image: require('../../assets/RankBadges/expert.png'),
    range: [263.5, 270.99],
    title: 'Peak Commander',
  },
  {
    level: '76',
    group: 'Expert',
    image: require('../../assets/RankBadges/expert.png'),
    range: [271.0, 278.49],
    title: 'Trailblazing Prodigy',
  },
  {
    level: '77',
    group: 'Expert',
    image: require('../../assets/RankBadges/expert.png'),
    range: [278.5, 285.99],
    title: 'Canyon Captain',
  },
  {
    level: '78',
    group: 'Expert',
    image: require('../../assets/RankBadges/expert.png'),
    range: [286.0, 293.49],
    title: 'Nature Oracle',
  },
  {
    level: '79',
    group: 'Expert',
    image: require('../../assets/RankBadges/expert.png'),
    range: [293.5, 300.99],
    title: 'Expedition Expert',
  },
  //
  {
    level: '80',
    group: 'Elite',
    image: require('../../assets/RankBadges/elite.png'),
    range: [301.0, 308.99],
    title: 'Summit Sovereign',
  },
  {
    level: '81',
    group: 'Elite',
    image: require('../../assets/RankBadges/elite.png'),
    range: [309.0, 316.99],
    title: 'Master Mountaineer',
  },
  {
    level: '82',
    group: 'Elite',
    image: require('../../assets/RankBadges/elite.png'),
    range: [317.0, 324.99],
    title: 'Trailblazing Ambassador',
  },
  {
    level: '83',
    group: 'Elite',
    image: require('../../assets/RankBadges/elite.png'),
    range: [325.0, 332.99],
    title: 'Canyon Connoisseur',
  },
  {
    level: '84',
    group: 'Elite',
    image: require('../../assets/RankBadges/elite.png'),
    range: [333.0, 340.99],
    title: 'Wilderness Sage',
  },
  {
    level: '85',
    group: 'Elite',
    image: require('../../assets/RankBadges/elite.png'),
    range: [341.0, 349.49],
    title: 'Scenic Conqueror',
  },
  {
    level: '86',
    group: 'Elite',
    image: require('../../assets/RankBadges/elite.png'),
    range: [349.5, 357.99],
    title: 'Peak Prodigy',
  },
  {
    level: '87',
    group: 'Elite',
    image: require('../../assets/RankBadges/elite.png'),
    range: [358.0, 366.49],
    title: 'Alpine Authority',
  },
  {
    level: '88',
    group: 'Elite',
    image: require('../../assets/RankBadges/elite.png'),
    range: [366.5, 374.99],
    title: 'Nature Virtuoso',
  },
  {
    level: '89',
    group: 'Elite',
    image: require('../../assets/RankBadges/elite.png'),
    range: [375.0, 383.49],
    title: 'Expedition Elite',
  },
  //
  {
    level: '90',
    group: 'Legendary',
    image: require('../../assets/RankBadges/legendary.png'),
    range: [383.5, 392.49],
    title: 'Summit Luminary',
  },
  {
    level: '91',
    group: 'Legendary',
    image: require('../../assets/RankBadges/legendary.png'),
    range: [392.5, 401.49],
    title: 'Grand Trailblazer',
  },
  {
    level: '92',
    group: 'Legendary',
    image: require('../../assets/RankBadges/legendary.png'),
    range: [401.5, 410.49],
    title: 'Peak Legend',
  },
  {
    level: '93',
    group: 'Legendary',
    image: require('../../assets/RankBadges/legendary.png'),
    range: [410.5, 419.49],
    title: 'Canyon Commander',
  },
  {
    level: '94',
    group: 'Legendary',
    image: require('../../assets/RankBadges/legendary.png'),
    range: [419.5, 428.49],
    title: 'Wilderness Guardian',
  },
  {
    level: '95',
    group: 'Legendary',
    image: require('../../assets/RankBadges/legendary.png'),
    range: [428.5, 442.79],
    title: 'Scenic Master',
  },
  {
    level: '96',
    group: 'Legendary',
    image: require('../../assets/RankBadges/legendary.png'),
    range: [442.8, 457.09],
    title: 'Alpine Legend',
  },
  {
    level: '97',
    group: 'Legendary',
    image: require('../../assets/RankBadges/legendary.png'),
    range: [457.1, 471.39],
    title: 'Exploration Titan',
  },
  {
    level: '98',
    group: 'Legendary',
    image: require('../../assets/RankBadges/legendary.png'),
    range: [471.4, 485.69],
    title: 'Summit Conqueror',
  },
  {
    level: '99',
    group: 'Legendary',
    image: require('../../assets/RankBadges/legendary.png'),
    range: [485.7, 499.99],
    title: 'Nature Luminary',
  },
  {
    level: '100',
    group: 'Legendary',
    image: require('../../assets/RankBadges/legendary.png'),
    range: [500.0, Infinity],
    title: 'Ultimate Trailblazer',
  },
  //?Unlock 24 mile hike for those that get lvl 99 (This hike is the only hike that can be done until lvl 100)
];

export default Ranks;
