const InitialBadges = [
    {id: '1',park_id:'1', badge_name: 'Acadia', badge_type: 'park'},
    {id: '2',park_id:'2', badge_name: 'American Samoa', badge_type: 'park'},
    {id: '3',park_id:'3', badge_name: 'Arches', badge_type: 'park'},
    {id: '4',park_id:'4', badge_name: 'Badlands', badge_type: 'park'},
    {id: '5',park_id:'5', badge_name: 'Big Bend', badge_type: 'park'},
    {id: '6',park_id:'6', badge_name: 'Biscayne', badge_type: 'park'},
    {id: '7',park_id:'7',badge_name: 'Black Canyon of the Gunnison',badge_type: 'park'},
    {id: '8',park_id:'8', badge_name: 'Bryce Canyon', badge_type: 'park'},
    {id: '9',park_id:'9', badge_name: 'Canyonlands', badge_type: 'park'},
    {id: '10',park_id:'10', badge_name: 'Capitol Reef', badge_type: 'park'},
    {id: '11',park_id:'11', badge_name: 'Carlsbad Caverns', badge_type: 'park'},
    {id: '12',park_id:'12', badge_name: 'Channel Islands', badge_type: 'park'},
    {id: '13',park_id:'13', badge_name: 'Congaree', badge_type: 'park'},
    {id: '14',park_id:'14', badge_name: 'Crater Lake', badge_type: 'park'},
    {id: '15',park_id:'15', badge_name: 'Cuyahoga Valley', badge_type: 'park'},
    {id: '16',park_id:'16', badge_name: 'Death Valley', badge_type: 'park'},
    {id: '17',park_id:'17', badge_name: 'Denali', badge_type: 'park'},
    {id: '18',park_id:'18', badge_name: 'Dry Tortugas', badge_type: 'park'},
    {id: '19',park_id:'19', badge_name: 'Everglades', badge_type: 'park'},
    {id: '20',park_id:'20',badge_name: 'Gates of the Arctic',badge_type: 'park'},
    {id: '21',park_id:'21', badge_name: 'Gateway Arch', badge_type: 'park'},
    {id: '22',park_id:'22', badge_name: 'Glacier Bay', badge_type: 'park'},
    {id: '23',park_id:'23', badge_name: 'Glacier', badge_type: 'park'},
    {id: '24',park_id:'24', badge_name: 'Grand Canyon', badge_type: 'park'},
    {id: '25',park_id:'25', badge_name: 'Grand Teton', badge_type: 'park'},
    {id: '26',park_id:'26', badge_name: 'Great Basin', badge_type: 'park'},
    {id: '27',park_id:'27', badge_name: 'Great Sand Dunes', badge_type: 'park'},
    {id: '28',park_id:'28',badge_name: 'Great Smoky Mountains',badge_type: 'park'},
    {id: '29',park_id:'29',badge_name: 'Guadalupe Mountains',badge_type: 'park'},
    {id: '30',park_id:'30', badge_name: 'Haleakala', badge_type: 'park'},
    {id: '31',park_id:'31', badge_name: 'Hawaii Volcanoes', badge_type: 'park'},
    {id: '32',park_id:'32', badge_name: 'Hot Springs', badge_type: 'park'},
    {id: '33',park_id:'33', badge_name: 'Indiana Dunes', badge_type: 'park'},
    {id: '34',park_id:'34', badge_name: 'Isle Royale', badge_type: 'park'},
    {id: '35',park_id:'35', badge_name: 'Joshua Tree', badge_type: 'park'},
    {id: '36',park_id:'36', badge_name: 'Katmai', badge_type: 'park'},
    {id: '37',park_id:'37', badge_name: 'Kenai Fjords', badge_type: 'park'},
    {id: '38',park_id:'38', badge_name: 'Kings Canyon', badge_type: 'park'},
    {id: '39',park_id:'39', badge_name: 'Kobuk Valley', badge_type: 'park'},
    {id: '40',park_id:'40', badge_name: 'Lake Clark', badge_type: 'park'},
    {id: '41',park_id:'41', badge_name: 'Lassen Volcanic', badge_type: 'park'},
    {id: '42',park_id:'42', badge_name: 'Mammoth Cave', badge_type: 'park'},
    {id: '43',park_id:'43', badge_name: 'Mesa Verde', badge_type: 'park'},
    {id: '44',park_id:'44', badge_name: 'Mount Rainier', badge_type: 'park'},
    {id: '45',park_id:'45', badge_name: 'New River Gorge', badge_type: 'park'},
    {id: '46',park_id:'46', badge_name: 'North Cascades', badge_type: 'park'},
    {id: '47',park_id:'47', badge_name: 'Olympic', badge_type: 'park'},
    {id: '48',park_id:'48', badge_name: 'Petrified Forest', badge_type: 'park'},
    {id: '49',park_id:'49', badge_name: 'Pinnacles', badge_type: 'park'},
    {id: '50',park_id:'50', badge_name: 'Redwood', badge_type: 'park'},
    {id: '51',park_id:'51', badge_name: 'Rocky Mountain', badge_type: 'park'},
    {id: '52',park_id:'52', badge_name: 'Saguaro', badge_type: 'park'},
    {id: '53',park_id:'53', badge_name: 'Sequoia', badge_type: 'park'},
    {id: '54',park_id:'54', badge_name: 'Shenandoah', badge_type: 'park'},
    {id: '55',park_id:'55',badge_name: 'Theodore Roosevelt',badge_type: 'park'},
    {id: '56',park_id:'56', badge_name: 'Virgin Islands', badge_type: 'park'},
    {id: '57',park_id:'57', badge_name: 'Voyageurs', badge_type: 'park'},
    {id: '58',park_id:'58', badge_name: 'White Sands', badge_type: 'park'},
    {id: '59',park_id:'59', badge_name: 'Wind Cave', badge_type: 'park'},
    {id: '60',park_id:'60',badge_name: 'Wrangell-St. Elias',badge_type: 'park'},
    {id: '61',park_id:'61', badge_name: 'Yellowstone', badge_type: 'park'},
    {id: '62',park_id:'62', badge_name: 'Yosemite', badge_type: 'park'},
    {id: '63',park_id:'63', badge_name: 'Zion', badge_type: 'park'},

]

export default InitialBadges
