const InitialBadges = [
    {id: '1',park_id:'1', name: 'Acadia', type: 'park'},
    {id: '2',park_id:'2', name: 'American Samoa', type: 'park'},
    {id: '3',park_id:'3', name: 'Arches', type: 'park'},
    {id: '4',park_id:'4', name: 'Badlands', type: 'park'},
    {id: '5',park_id:'5', name: 'Big Bend', type: 'park'},
    {id: '6',park_id:'6', name: 'Biscayne', type: 'park'},
    {id: '7',park_id:'7',name: 'Black Canyon of the Gunnison',type: 'park'},
    {id: '8',park_id:'8', name: 'Bryce Canyon', type: 'park'},
    {id: '9',park_id:'9', name: 'Canyonlands', type: 'park'},
    {id: '10',park_id:'10', name: 'Capitol Reef', type: 'park'},
    {id: '11',park_id:'11', name: 'Carlsbad Caverns', type: 'park'},
    {id: '12',park_id:'12', name: 'Channel Islands', type: 'park'},
    {id: '13',park_id:'13', name: 'Congaree', type: 'park'},
    {id: '14',park_id:'14', name: 'Crater Lake', type: 'park'},
    {id: '15',park_id:'15', name: 'Cuyahoga Valley', type: 'park'},
    {id: '16',park_id:'16', name: 'Death Valley', type: 'park'},
    {id: '17',park_id:'17', name: 'Denali', type: 'park'},
    {id: '18',park_id:'18', name: 'Dry Tortugas', type: 'park'},
    {id: '19',park_id:'19', name: 'Everglades', type: 'park'},
    {id: '20',park_id:'20',name: 'Gates of the Arctic',type: 'park'},
    {id: '21',park_id:'21', name: 'Gateway Arch', type: 'park'},
    {id: '22',park_id:'22', name: 'Glacier Bay', type: 'park'},
    {id: '23',park_id:'23', name: 'Glacier', type: 'park'},
    {id: '24',park_id:'24', name: 'Grand Canyon', type: 'park'},
    {id: '25',park_id:'25', name: 'Grand Teton', type: 'park'},
    {id: '26',park_id:'26', name: 'Great Basin', type: 'park'},
    {id: '27',park_id:'27', name: 'Great Sand Dunes', type: 'park'},
    {id: '28',park_id:'28',name: 'Great Smoky Mountains',type: 'park'},
    {id: '29',park_id:'29',name: 'Guadalupe Mountains',type: 'park'},
    {id: '30',park_id:'30', name: 'Haleakala', type: 'park'},
    {id: '31',park_id:'31', name: 'Hawaii Volcanoes', type: 'park'},
    {id: '32',park_id:'32', name: 'Hot Springs', type: 'park'},
    {id: '33',park_id:'33', name: 'Indiana Dunes', type: 'park'},
    {id: '34',park_id:'34', name: 'Isle Royale', type: 'park'},
    {id: '35',park_id:'35', name: 'Joshua Tree', type: 'park'},
    {id: '36',park_id:'36', name: 'Katmai', type: 'park'},
    {id: '37',park_id:'37', name: 'Kenai Fjords', type: 'park'},
    {id: '38',park_id:'38', name: 'Kings Canyon', type: 'park'},
    {id: '39',park_id:'39', name: 'Kobuk Valley', type: 'park'},
    {id: '40',park_id:'40', name: 'Lake Clark', type: 'park'},
    {id: '41',park_id:'41', name: 'Lassen Volcanic', type: 'park'},
    {id: '42',park_id:'42', name: 'Mammoth Cave', type: 'park'},
    {id: '43',park_id:'43', name: 'Mesa Verde', type: 'park'},
    {id: '44',park_id:'44', name: 'Mount Rainier', type: 'park'},
    {id: '45',park_id:'45', name: 'New River Gorge', type: 'park'},
    {id: '46',park_id:'46', name: 'North Cascades', type: 'park'},
    {id: '47',park_id:'47', name: 'Olympic', type: 'park'},
    {id: '48',park_id:'48', name: 'Petrified Forest', type: 'park'},
    {id: '49',park_id:'49', name: 'Pinnacles', type: 'park'},
    {id: '50',park_id:'50', name: 'Redwood', type: 'park'},
    {id: '51',park_id:'51', name: 'Rocky Mountain', type: 'park'},
    {id: '52',park_id:'52', name: 'Saguaro', type: 'park'},
    {id: '53',park_id:'53', name: 'Sequoia', type: 'park'},
    {id: '54',park_id:'54', name: 'Shenandoah', type: 'park'},
    {id: '55',park_id:'55',name: 'Theodore Roosevelt',type: 'park'},
    {id: '56',park_id:'56', name: 'Virgin Islands', type: 'park'},
    {id: '57',park_id:'57', name: 'Voyageurs', type: 'park'},
    {id: '58',park_id:'58', name: 'White Sands', type: 'park'},
    {id: '59',park_id:'59', name: 'Wind Cave', type: 'park'},
    {id: '60',park_id:'60',name: 'Wrangell-St. Elias',type: 'park'},
    {id: '61',park_id:'61', name: 'Yellowstone', type: 'park'},
    {id: '62',park_id:'62', name: 'Yosemite', type: 'park'},
    {id: '63',park_id:'63', name: 'Zion', type: 'park'},
]

export default InitialBadges
