const initialSessionCategories = [
  {id: '1', session_category_name: 'Chores'},
  {id: '2', session_category_name: 'Cooking'},
  {id: '3', session_category_name: 'Crafts'},
  {id: '4', session_category_name: 'DIY Project'},
  {id: '5', session_category_name: 'Drawing'},
  {id: '6', session_category_name: 'Driving'},
  {id: '7', session_category_name: 'Errands'},
  {id: '8', session_category_name: 'Family'},
  {id: '9', session_category_name: 'Finance'},
  {id: '10', session_category_name: 'Gaming'},
  {id: '11', session_category_name: 'Gardening'},
  {id: '12', session_category_name: 'Gym'},
  {id: '13', session_category_name: 'Hiking'},
  {id: '14', session_category_name: 'Learning'},
  {id: '15', session_category_name: 'Meditating'},
  {id: '16', session_category_name: 'Music'},
  {id: '17', session_category_name: 'Other'},
  {id: '18', session_category_name: 'Outdoors'},
  {id: '19', session_category_name: 'Personal Projects'},
  {id: '20', session_category_name: 'Pets'},
  {id: '21', session_category_name: 'Photography'},
  {id: '22', session_category_name: 'Planning'},
  {id: '23', session_category_name: 'Reading'},
  {id: '24', session_category_name: 'Self Care'},
  {id: '25', session_category_name: 'Social'},
  {id: '26', session_category_name: 'Sports'},
  {id: '27', session_category_name: 'Study'},
  {id: '28', session_category_name: 'Work'},
  {id: '29', session_category_name: 'Workout'},
  {id: '30', session_category_name: 'Writing'},
  {id: '31', session_category_name: 'Volunteering'},
  {id: '32', session_category_name: 'Yoga'},
];
export default initialSessionCategories;
